//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Part5.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ConvertCaseSoap")]
    public interface ConvertCaseSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Part5.ServiceReference1.HelloWorldResponse HelloWorld(Part5.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Part5.ServiceReference1.HelloWorldResponse> HelloWorldAsync(Part5.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name word from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ToLowerCase", ReplyAction="*")]
        Part5.ServiceReference1.ToLowerCaseResponse ToLowerCase(Part5.ServiceReference1.ToLowerCaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ToLowerCase", ReplyAction="*")]
        System.Threading.Tasks.Task<Part5.ServiceReference1.ToLowerCaseResponse> ToLowerCaseAsync(Part5.ServiceReference1.ToLowerCaseRequest request);
        
        // CODEGEN: Generating message contract since element name word from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ToUpperCase", ReplyAction="*")]
        Part5.ServiceReference1.ToUpperCaseResponse ToUpperCase(Part5.ServiceReference1.ToUpperCaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ToUpperCase", ReplyAction="*")]
        System.Threading.Tasks.Task<Part5.ServiceReference1.ToUpperCaseResponse> ToUpperCaseAsync(Part5.ServiceReference1.ToUpperCaseRequest request);
        
        // CODEGEN: Generating message contract since element name word from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InvertCase", ReplyAction="*")]
        Part5.ServiceReference1.InvertCaseResponse InvertCase(Part5.ServiceReference1.InvertCaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InvertCase", ReplyAction="*")]
        System.Threading.Tasks.Task<Part5.ServiceReference1.InvertCaseResponse> InvertCaseAsync(Part5.ServiceReference1.InvertCaseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Part5.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Part5.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Part5.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Part5.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ToLowerCaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ToLowerCase", Namespace="http://tempuri.org/", Order=0)]
        public Part5.ServiceReference1.ToLowerCaseRequestBody Body;
        
        public ToLowerCaseRequest() {
        }
        
        public ToLowerCaseRequest(Part5.ServiceReference1.ToLowerCaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ToLowerCaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string word;
        
        public ToLowerCaseRequestBody() {
        }
        
        public ToLowerCaseRequestBody(string word) {
            this.word = word;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ToLowerCaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ToLowerCaseResponse", Namespace="http://tempuri.org/", Order=0)]
        public Part5.ServiceReference1.ToLowerCaseResponseBody Body;
        
        public ToLowerCaseResponse() {
        }
        
        public ToLowerCaseResponse(Part5.ServiceReference1.ToLowerCaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ToLowerCaseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ToLowerCaseResult;
        
        public ToLowerCaseResponseBody() {
        }
        
        public ToLowerCaseResponseBody(string ToLowerCaseResult) {
            this.ToLowerCaseResult = ToLowerCaseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ToUpperCaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ToUpperCase", Namespace="http://tempuri.org/", Order=0)]
        public Part5.ServiceReference1.ToUpperCaseRequestBody Body;
        
        public ToUpperCaseRequest() {
        }
        
        public ToUpperCaseRequest(Part5.ServiceReference1.ToUpperCaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ToUpperCaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string word;
        
        public ToUpperCaseRequestBody() {
        }
        
        public ToUpperCaseRequestBody(string word) {
            this.word = word;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ToUpperCaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ToUpperCaseResponse", Namespace="http://tempuri.org/", Order=0)]
        public Part5.ServiceReference1.ToUpperCaseResponseBody Body;
        
        public ToUpperCaseResponse() {
        }
        
        public ToUpperCaseResponse(Part5.ServiceReference1.ToUpperCaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ToUpperCaseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ToUpperCaseResult;
        
        public ToUpperCaseResponseBody() {
        }
        
        public ToUpperCaseResponseBody(string ToUpperCaseResult) {
            this.ToUpperCaseResult = ToUpperCaseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvertCaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvertCase", Namespace="http://tempuri.org/", Order=0)]
        public Part5.ServiceReference1.InvertCaseRequestBody Body;
        
        public InvertCaseRequest() {
        }
        
        public InvertCaseRequest(Part5.ServiceReference1.InvertCaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InvertCaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string word;
        
        public InvertCaseRequestBody() {
        }
        
        public InvertCaseRequestBody(string word) {
            this.word = word;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvertCaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvertCaseResponse", Namespace="http://tempuri.org/", Order=0)]
        public Part5.ServiceReference1.InvertCaseResponseBody Body;
        
        public InvertCaseResponse() {
        }
        
        public InvertCaseResponse(Part5.ServiceReference1.InvertCaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InvertCaseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InvertCaseResult;
        
        public InvertCaseResponseBody() {
        }
        
        public InvertCaseResponseBody(string InvertCaseResult) {
            this.InvertCaseResult = InvertCaseResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConvertCaseSoapChannel : Part5.ServiceReference1.ConvertCaseSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConvertCaseSoapClient : System.ServiceModel.ClientBase<Part5.ServiceReference1.ConvertCaseSoap>, Part5.ServiceReference1.ConvertCaseSoap {
        
        public ConvertCaseSoapClient() {
        }
        
        public ConvertCaseSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConvertCaseSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConvertCaseSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConvertCaseSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Part5.ServiceReference1.HelloWorldResponse Part5.ServiceReference1.ConvertCaseSoap.HelloWorld(Part5.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Part5.ServiceReference1.HelloWorldRequest inValue = new Part5.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Part5.ServiceReference1.HelloWorldRequestBody();
            Part5.ServiceReference1.HelloWorldResponse retVal = ((Part5.ServiceReference1.ConvertCaseSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Part5.ServiceReference1.HelloWorldResponse> Part5.ServiceReference1.ConvertCaseSoap.HelloWorldAsync(Part5.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Part5.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            Part5.ServiceReference1.HelloWorldRequest inValue = new Part5.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Part5.ServiceReference1.HelloWorldRequestBody();
            return ((Part5.ServiceReference1.ConvertCaseSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Part5.ServiceReference1.ToLowerCaseResponse Part5.ServiceReference1.ConvertCaseSoap.ToLowerCase(Part5.ServiceReference1.ToLowerCaseRequest request) {
            return base.Channel.ToLowerCase(request);
        }
        
        public string ToLowerCase(string word) {
            Part5.ServiceReference1.ToLowerCaseRequest inValue = new Part5.ServiceReference1.ToLowerCaseRequest();
            inValue.Body = new Part5.ServiceReference1.ToLowerCaseRequestBody();
            inValue.Body.word = word;
            Part5.ServiceReference1.ToLowerCaseResponse retVal = ((Part5.ServiceReference1.ConvertCaseSoap)(this)).ToLowerCase(inValue);
            return retVal.Body.ToLowerCaseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Part5.ServiceReference1.ToLowerCaseResponse> Part5.ServiceReference1.ConvertCaseSoap.ToLowerCaseAsync(Part5.ServiceReference1.ToLowerCaseRequest request) {
            return base.Channel.ToLowerCaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<Part5.ServiceReference1.ToLowerCaseResponse> ToLowerCaseAsync(string word) {
            Part5.ServiceReference1.ToLowerCaseRequest inValue = new Part5.ServiceReference1.ToLowerCaseRequest();
            inValue.Body = new Part5.ServiceReference1.ToLowerCaseRequestBody();
            inValue.Body.word = word;
            return ((Part5.ServiceReference1.ConvertCaseSoap)(this)).ToLowerCaseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Part5.ServiceReference1.ToUpperCaseResponse Part5.ServiceReference1.ConvertCaseSoap.ToUpperCase(Part5.ServiceReference1.ToUpperCaseRequest request) {
            return base.Channel.ToUpperCase(request);
        }
        
        public string ToUpperCase(string word) {
            Part5.ServiceReference1.ToUpperCaseRequest inValue = new Part5.ServiceReference1.ToUpperCaseRequest();
            inValue.Body = new Part5.ServiceReference1.ToUpperCaseRequestBody();
            inValue.Body.word = word;
            Part5.ServiceReference1.ToUpperCaseResponse retVal = ((Part5.ServiceReference1.ConvertCaseSoap)(this)).ToUpperCase(inValue);
            return retVal.Body.ToUpperCaseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Part5.ServiceReference1.ToUpperCaseResponse> Part5.ServiceReference1.ConvertCaseSoap.ToUpperCaseAsync(Part5.ServiceReference1.ToUpperCaseRequest request) {
            return base.Channel.ToUpperCaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<Part5.ServiceReference1.ToUpperCaseResponse> ToUpperCaseAsync(string word) {
            Part5.ServiceReference1.ToUpperCaseRequest inValue = new Part5.ServiceReference1.ToUpperCaseRequest();
            inValue.Body = new Part5.ServiceReference1.ToUpperCaseRequestBody();
            inValue.Body.word = word;
            return ((Part5.ServiceReference1.ConvertCaseSoap)(this)).ToUpperCaseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Part5.ServiceReference1.InvertCaseResponse Part5.ServiceReference1.ConvertCaseSoap.InvertCase(Part5.ServiceReference1.InvertCaseRequest request) {
            return base.Channel.InvertCase(request);
        }
        
        public string InvertCase(string word) {
            Part5.ServiceReference1.InvertCaseRequest inValue = new Part5.ServiceReference1.InvertCaseRequest();
            inValue.Body = new Part5.ServiceReference1.InvertCaseRequestBody();
            inValue.Body.word = word;
            Part5.ServiceReference1.InvertCaseResponse retVal = ((Part5.ServiceReference1.ConvertCaseSoap)(this)).InvertCase(inValue);
            return retVal.Body.InvertCaseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Part5.ServiceReference1.InvertCaseResponse> Part5.ServiceReference1.ConvertCaseSoap.InvertCaseAsync(Part5.ServiceReference1.InvertCaseRequest request) {
            return base.Channel.InvertCaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<Part5.ServiceReference1.InvertCaseResponse> InvertCaseAsync(string word) {
            Part5.ServiceReference1.InvertCaseRequest inValue = new Part5.ServiceReference1.InvertCaseRequest();
            inValue.Body = new Part5.ServiceReference1.InvertCaseRequestBody();
            inValue.Body.word = word;
            return ((Part5.ServiceReference1.ConvertCaseSoap)(this)).InvertCaseAsync(inValue);
        }
    }
}
